### Get all tasks
GET http://localhost:3000/tasks

### Get filtered tasks
GET http://localhost:3000/tasks?search=sometask

### Create a new task
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "task 31",
  "description": "task 31"
}

### Get a task by id
GET http://localhost:3000/tasks/7868ff6d-220c-4206-b139-2e025965e917

### Delete a task
DELETE http://localhost:3000/tasks/7868ff6d-220c-4206-b139-2e025965e917

### Update a task
PATCH http://localhost:3000/tasks/79dc9b96-ef98-405d-986a-86900e9c9dbc
Content-Type: application/json

{
  "status": "IN_PROGRESS"
}
